apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-service
  description: A demo Express.js service for Backstage integration
  annotations:
    github.com/project-slug: chandrashekhar-appointy/backstage-component
    backstage.io/techdocs-ref: dir:.
  tags:
    - nodejs
    - express
    - demo
  links:
    - url: https://github.com/chandrashekhar-appointy/backstage-component
      title: GitHub Repository
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: demo-system
  providesApis:
    - demo-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-api
  description: REST API for demo service
spec:
  type: openapi
  lifecycle: experimental
  owner: team-a
  system: demo-system
  definition: |
    openapi: 3.0.0
    info:
      title: Demo Service API
      version: 1.0.0
      description: A simple demo API
    paths:
      /:
        get:
          summary: Welcome message
          responses:
            '200':
              description: Welcome response
      /health:
        get:
          summary: Health check
          responses:
            '200':
              description: Service health status
      /api/info:
        get:
          summary: Service information
          responses:
            '200':
              description: Service metadata and endpoints
