steps:
  # Step 1: Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install']
    id: 'install-dependencies'

  # Step 2: Run tests
  - name: 'node:18'
    entrypoint: npm
    args: ['test']
    id: 'run-tests'
    waitFor: ['install-dependencies']

  # Step 3: Display Node and npm versions
  - name: 'node:18'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "Build completed successfully!"
        node --version
        npm --version
    id: 'build-info'
    waitFor: ['run-tests']

  # Step 4: Echo success message
  - name: 'node:18'
    entrypoint: echo
    args: ['✓ Cloud Build pipeline completed successfully for demo-service']
    id: 'success-message'
    waitFor: ['build-info']

# Build timeout
timeout: '600s'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Tags for the build
tags:
  - 'demo-service'
  - 'nodejs'
  - 'backstage'
