steps:
  # Step 1: Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['install']
    id: 'install-dependencies'

  # Step 2: Run tests
  - name: 'node:18'
    entrypoint: npm
    args: ['test']
    id: 'run-tests'
    waitFor: ['install-dependencies']

  # Step 3: Display Node and npm versions
  - name: 'node:18'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "Build completed successfully!"
        node --version
        npm --version
    id: 'build-info'
    waitFor: ['run-tests']

  # Step 4: Echo success message
  - name: 'node:18'
    entrypoint: echo
    args: ['✓ Cloud Build pipeline completed successfully for demo-service']
    id: 'success-message'
    waitFor: ['build-info']

  # Step 5: Generate output folder with index.html
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']
    id: 'generate-output'
    waitFor: ['success-message']

  # Step 6: Upload output folder to GCS bucket (private)
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-r'
      - '-d'
      - 'output/'
      - 'gs://testingformemyself/'
    id: 'upload-to-gcs'
    waitFor: ['generate-output']

  # Step 7: Send Slack notification with GCS URL
  - name: 'curlimages/curl:latest'
    entrypoint: 'sh'
    secretEnv: ['SLACK_WEBHOOK_URL']
    args:
      - '-c'
      - |
        curl -X POST $SLACK_WEBHOOK_URL \
          -H 'Content-Type: application/json' \
          -d "{\"text\":\"✅ *Build Success!*\n🎨 Demo Service deployed\n🔗 View: https://console.cloud.google.com/storage/browser/_details/testingformemyself/index.html?project=focal-psyche-460009-a5\n📦 Build ID: ${BUILD_ID}\n🌿 Branch: ${BRANCH_NAME}\n📝 Commit: ${SHORT_SHA}\"}"
    id: 'send-slack-notification'
    waitFor: ['upload-to-gcs']

# Build timeout
timeout: '600s'

# Secret Manager secrets
availableSecrets:
  secretManager:
    - versionName: projects/339960399182/secrets/backstage-component-bucket-secret/versions/latest
      env: 'SLACK_WEBHOOK_URL'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Tags for the build
tags:
  - 'demo-service'
  - 'nodejs'
  - 'backstage'
